<?php
// index.php

require('config.php');
setlocale(LC_ALL, LANGUAGE);
bindtextdomain('sysstatgraph', './locale');
bind_textdomain_codeset('sysstatgraph', 'UTF-8');
textdomain('sysstatgraph');

require('library/GenerateStatData.php');
require('library/ImportStatFileData.php');
require('library/BuildJsonStructure.php');

$generate_stat_data = new GenerateStatData();
$generate_stat_data->execute(STAT_DAYS);
$statdata = '{}';
if (is_file(JSONSTRUCTUREFILENAME)) {
    $statdata = file_get_contents(JSONSTRUCTUREFILENAME);
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="zh" xml:lang="zh">
<head>
	<title><?php echo _('SysStat Graph'); ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="text/javascript" src="assets/sysstatgraph.zh.js"></script>
	<script type="text/javascript" src="assets/rendergraph.js"></script>
	<script type="text/javascript" src="assets/tocbox.js"></script>
	<link rel="stylesheet" type="text/css" href="assets/style.css" />
</head>

<body>

	<h1><?php echo _('SysStat Graph'); ?></h1>

	<div id="content"></div>

	<p><?php echo _('Generated by') . ' '; ?><a href="http://magnetikonline.com/sysstatgraph/"><?php echo _('SysStat Graph') . ' ' . _('Version') . ' '; ?>0.5</a></p>

	<script type="text/javascript">
	sysstatgraph.statdata = <?php echo $statdata; ?>;
	sysstatgraph.init();
	</script>

</body>
</html>
