<?php
// index.php

require('config.php');
setlocale(LC_ALL, LANGUAGE);
bindtextdomain('sysstatgraph', './locale');

require('library/generatestatdata.php');
require('library/importstatfiledata.php');
require('library/buildjsonstructure.php');



$generatestatdata = new generatestatdata();
$generatestatdata->execute();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<title><?php echo _('SysStat Graph'); ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="text/javascript" src="assets/sysstatgraph.js"></script>
	<script type="text/javascript" src="assets/rendergraph.js"></script>
	<script type="text/javascript" src="assets/tocbox.js"></script>
	<link rel="stylesheet" type="text/css" href="assets/style.css" />
</head>

<body>

	<h1><?php echo _('SysStat Graph'); ?></h1>

	<div id="content"></div>

	<p><?php echo _('Generated by '); ?><a href="http://magnetikonline.com/sysstatgraph/"><?php echo _('SysStat Graph') . ' ' . _('Version') . ' '; ?>0.4</a></p>

	<script type="text/javascript">
	sysstatgraph.statdata = <?php echo((is_file(JSONSTRUCTUREFILENAME)) ? file_get_contents(JSONSTRUCTUREFILENAME) : '{}'); ?>;
	sysstatgraph.init();
	</script>

</body>
</html>
